### ISSUE TITLE
Update to PHPCS3 conventions

### ISSUE THREAD

**Issue by BPScott** [djoos/Symfony2-coding-standard#61]
[PHPCS 3.0 was released the other day](https://github.com/squizlabs/PHP_CodeSniffer/releases/tag/3.0.0) 🎉  however it breaks backwards compatibility with all custom sniffs. There is [an upgrade guide](https://github.com/squizlabs/PHP_CodeSniffer/wiki/Version-3.0-Upgrade-Guide) to move from 2.x to 3.x.

In order for people to migrate to PHPCS3 all existing sniffs shall need to be migrated.

**Comment by wickedOne** [comment]
i'm willing to invest some time to make a phpcs v3 version, but i'm not entirely sure of the livelyness of this repo.

@djoos what are your intentions with this repo? 
#32 has been open for quite a while and appears to be a blocker for all open pull requests (appears as in: they're open without any comment since #32 was opened).

are you willing to transfer ownership / add some members to this repo to keep it in a more active state?

**Comment by djoos** [comment]
Hi guys,

there are some open issues - but the repo is definitely still alive ;-)
We've had some issues and PRs flow through after #32 and definitely happy to merge in PRs quickly if they are concise.

It would be good to discuss adding additional members at some point though - and it would be great to get the open issues and PRs sorted/closed...

Hope this helps!

**Comment by wickedOne** [comment]
thanks @djoos, thats goo news!
i'll try and prep a phpcs v3 compatible version somewhere in the next couple of weeks using the v.2.10.1 release as baseand we'll go from there...

**Comment by djoos** [comment]
@WickedOne, that sounds great!

Just a heads up: please try to keep the changes [atomic](https://seesparkbox.com/foundry/atomic_commits_with_git) by just implementing the phpcs v3 compatibility.
I'm happy to get other things that might pop up merged in via additional PRs though!

Thanks in advance!
David

**Comment by wickedOne** [comment]
@djoos: no worries, i won't try to sneak in new or altered sniffs :-)
reading the upgrade guide, v3 looks like a fairly simple refactor
